### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'

### ISSUE THREAD

**Issue by antvillagehead** [FrozenBurning/SceneDreamer#11]
When I configured the environment, a problem occurred in the following steps：

```
for p in gancraft/voxlib; do
 cd imaginaire/model_utils/${p};
 make all
 cd ${CURRENT};
 done
```
Here's the error
```
python setup.py build_ext --inplace
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
running build_ext
building 'voxlib' extension
Traceback (most recent call last):
  File "/home/ant/SceneDreamer/imaginaire/model_utils/gancraft/voxlib/setup.py", line 11, in <module>
    setup(
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/ant/anaconda3/envs/scenedreamer/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
make: *** [Makefile:7：all] 错误 1
```

It has been bothering me for a long time, and I don't know how to solve it.
My cuda path is as follows

```
(scenedreamer) ant@AntPC:~/SceneDreamer$ echo $CUDA_HOME
/usr/local/cuda-11.3
(scenedreamer) ant@AntPC:~/SceneDreamer$ echo $PATH
/usr/local/cuda-11.3/bin:/home/ant/anaconda3/envs/scenedreamer/bin:/home/ant/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(scenedreamer) ant@AntPC:~/SceneDreamer$ echo $LD_LIBRARY_PATH
/usr/local/cuda-11.3/lib64:
```

**Comment by FrozenBurning** [comment]
Hey, thanks for your interest in SceneDreamer! According to my experience, this issue is related to low-end GPU arches. Try this prefix `TORCH_CUDA_ARCH_LIST="7.0+PTX"` when running python -m pip install .
